googleapis/nodejs-logging

.circleci/config.yml

This will make system and sample tests pass on CircleCI.
Note: This PR _must_ precede the 1.1.0 release, as the release workflow will fail otherwise (as well it should).

Fix CI configuration glitches.

---

src/metadata.js
test/metadata.js

correctly locate gcp-metadata property

---

synth.py

Update synth.py, removing generate-scaffolding

---

synth.py

setup: just npm ci in synth.py

---

CHANGELOG.md
package.json

Release nodejs-logging v3.0.0

---

src/metadata.js
test/metadata.js

Fixes: https://github.com/googleapis/nodejs-logging/issues/27

fix(GCE): add zone label in GCE descriptor

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging v3.0.3

---

samples/fluent.js
src/entry.js
src/index.js
src/log.js
src/metadata.js
src/sink.js
system-test/logging.js
test/entry.js
test/index.js
test/log.js
test/metadata.js

Use arrow functions

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging v4.0.0

---

package.json

fix(deps): Upgrade to @google-cloud/common-grpc 0.9.0

---

package.json
system-test/logging.js

..and fix the system test failure on PRs.

fix(test): block auth during public system tests

---

package.json

The current glob was catching samples/node_modules.

fix(fix): no fix for samples/node_modules

---

src/index.ts
src/middleware/express/index.ts
src/middleware/index.ts

Export it here so that I can use it from `logging-{winston,bunyan}`.

feat: export middleware helpers

---

package.json

feat: include TypeScript types

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging v4.4.0

---

package.json

chore(deps): update @google-cloud/pubsub to v0.27.0

---

.gitignore
package.json
samples/.eslintrc.yml
src/entry.ts
src/index.ts
src/log.ts
src/sink.ts
system-test/logging.ts
test/entry.ts
test/index.ts
test/middleware/express/test-make-middleware.ts
test/middleware/test-context.ts

refactor: clean up types and imports

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging v4.5.0

---

.repo-metadata.json
README.md
synth.metadata

stackdriver logging has a free tier.

fix: there is a free tier for logging

---

.readme-partials.yml
README.md

Added note about batching together writes, to address latency concerns with logging.
Fixes #357

fix(docs): add note about batching writes

---

samples/quickstart.js

Don't instantiate Logging client every function invocation. b/141366779

feat(samples): increase Logging client scope

---

system-test/logging.ts

Fixes #417 
Following the instructions from the error email (see #417), this grants the proper permissions to the test bucket. Hopefully that stops the emails. I'm not really sure how to verify, because the emails don't seem to come instantly when there's an error. Hopefully, this is simply correct, and we can merge and wait and see :)

test: grant proper permissions to bucket destination

---

src/log.ts
test/log.ts

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #711 🦕

fix(types): write options dryRun and partialSuccess (#711)

---

samples/logs.js
src/index.ts

fix(docs): orderBy sample and documentation

---

.github/workflows/ci.yaml
.kokoro/samples-test.sh
.kokoro/system-test.sh
.kokoro/test.sh
.mocharc.js
.mocharc.json

This PR fixes a bug with our coverage collection, and adds support for Build Cop :tada:

build(test): adds support for build cop, fixes codecov.io

---

samples/test/quickstart.test.js
system-test/logging.ts
test/log.ts

ensure build-cop works before we go wide with config.

chore: test build cop

---

.mocharc.js

we need to actually export the config!

build: mocharc needs to export

---

src/index.ts
src/log.ts
src/sink.ts

fix(docs): documentation for overloaded methods

---

package.json
system-test/logging.ts

updating to UUID@7 requires a small code change.

chore: update uuid dependency

---

system-test/logging.ts

Fixes #753 
This will give more time to the tests that verify log entries are properly received.

test: allow appropriate waiting times

---

samples/quickstart.js

show folks how to set the severity level of a log message.

docs: demonstrate how to set log level

---

system-test/logging.ts

I think we will need to dig into this issue in isolation, but let's unblock other PRs in the mean time.

test: skip failing test until we can dig into the issue
