- package.json
> Add `protos` to published npm module.

- src/metadata.js
- test/metadata.js
GCF provides the region in the environment variable `FUNCTION_REGION`.
> fix: gcf: use correct envvar for region

- package.json
- samples/package.json
Need to release a new version to npm to upgrade dependencies on `@google-cloud/common`. The currently released version requires 0.15.x which is older than we need.
> releasing v1.1.3

- src/metadata.js
- test/metadata.js
Fixes #53
Fixes #68
Fixes #78
[gcp-metadata updated to promises](https://github.com/stephenplusplus/gcp-metadata/pull/24), but we didn't update our code.
> gcp-metadata uses promises.

- system-test/logging.js
Tests are failing randomly. I think this value that sets the delay between a write and a read is too small.
> Extend system test delay.

- src/index.js
- test/index.js
RE: #91 
I caught this while investigating #91. When we auto-paginate using the `nextQuery` object built by GAPIC, we constantly push the project ID resource to the `reqOpts.resourceNames` argument. So for each run, we end up with with a new, duplicate entry of `projects/my-project-id`.
This flattens them, as well as localizes the project ID returned by the auth client, so we can still flatten the array when the user is using ADC.
> fix: Unique-ify getEntries resourceNames

- src/metadata.js
- test/metadata.js
The value actually returned by google-auth-library is [`KUBERNETES_ENGINE`](https://github.com/google/google-auth-library-nodejs/blob/bad432105f5ad0203266e9c6b31d2235fc96534b/src/auth/envDetect.ts#L21).
This regressed in https://github.com/googleapis/nodejs-logging/pull/128.
> fix(gke): correctly detect kubernetes engine

- CHANGELOG.md
- package.json
> Release nodejs-logging v3.0.2

- README.md
- package.json
- samples/logs.js
- samples/package.json
- samples/quickstart.js
- samples/sinks.js
- samples/system-test/quickstart.test.js
- samples/system-test/sinks.test.js
- src/entry.js
- src/index.js
- src/log.js
- src/metadata.js
- src/sink.js
- src/v2/config_service_v2_client.js
- src/v2/logging_service_v2_client.js
- src/v2/metrics_service_v2_client.js
- system-test/logging.js
- test/entry.js
- test/index.js
- test/log.js
- test/metadata.js
- test/sink.js
BREAKING CHANGE: This library is now compatible with es module import syntax.  
```js
const logging = require('@google-cloud/logging')();
// or...
const Logging = require('@google-cloud/logging');
const logging = new Logging();
```
```js
const {Logging} = require('@google-cloud/logging');
const logging = new Logging();
```
> Use es classes

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/logging v4.0.1

- .clang-format
- package.json
- src/index.js
- src/v2/config_service_v2_client.js
- src/v2/logging_service_v2_client.js
- src/v2/metrics_service_v2_client.js
- synth.py
- system-test/logging.js
- test/index.js
- tsconfig.json
- tslint.json
Use TypeScript compiler with the `allowJs` option. With the toolchain
in place we can start migrating the files incrementally.
> refactor: introduce typescript compiler

- package.json
- system-test/logging.ts
`master` was not compiling on my machine. This change picks up the latest `@google-cloud/storage` package with fixed types. Secondly, the `getSinksStream` is inferred to be typed as a `Stream` which doesn't have an `end` method. Even a `Readable` is not supposed to have an `end` method. Either way, fix the compile error by papering over it.
> fix: resolve compile errors

- src/middleware/express/make-middleware.ts
- test/middleware/express/test-make-middleware.ts
* Child suffix is not necessary.
* Make emitRequestLog optional. Make it control finish tracking.
> fix(middleware): tweak the middleware api

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/logging v4.2.0

- package.json
- src/middleware/express/make-http-request.ts
- src/middleware/express/make-middleware.ts
- test/middleware/express/test-make-http-request.ts
We don't have a dependency on express. If we expose express types
as part of our public, our dependent modules will need to have a dev
dependency on @types/express. Otherwise they see their builds failing.
Currently there is no way to express this dependency relationship to
npm.
Instead, let's not use express types.
Ref: https://github.com/googleapis/nodejs-logging-bunyan/issues/243
> fix: stop exporting express types publicly

- src/metadata.ts
- test/metadata.ts
Strings can have typos. Use enum now that it is exported from
google-auth-library.
> chore: use proper enum for GCPEnv

- src/index.ts
- src/log.ts
`logging-{winston,bunyan}` need these extra types.
> refactor: expose and improve types

- src/index.ts
- src/metadata.ts
- test/metadata.ts
Ref: https://github.com/googleapis/nodejs-logging-bunyan/issues/135
> feat: ability to detect service context

- package.json
- proto/logging_config.d.ts
- src/index.ts
- src/log.ts
- src/sink.ts
- system-test/logging.ts
- test/index.ts
- test/sink.ts
> refactor (typescript): noImplilcitAny

- src/log.ts
- src/metadata.ts
- system-test/logging.ts
The system tests are trying to delete all buckets, datasets, topics, and sinks that match a given name pattern.  If the system tests run at the same time, this leads to weird errors and conflicts.  This PR tries to fix that :)
> test: reap deleted resources to avoid collisions

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/logging v4.5.1

- package.json
- src/entry.ts
Fixes: https://github.com/googleapis/nodejs-logging/issues/442
@bcoe I know you wanted to look at this bug too.  I had some spare cycles so I went ahead and implemented this. LMK if you have another fix already prepared, or have something more holistic about the types we expose across all of the library. We can close this one in that case.
> fix(types): improve types for LogEntry

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/logging v4.5.2

- src/sink.ts
- test/sink.ts
Towards #390
Refactor: `sink.ts` to async-first
> refactor: sink.ts to async-first

- system-test/logging.ts
* tests were unable to be run in isolation due to a log line being created globally.
* I believe the other issue might have been a change in the way `mocha` handles hanging promises, we didn't `await` or return an async write.
fixes #542
> test: address a couple minor issues with system tests

- package.json
- src/index.ts
- src/log.ts
- src/v2/config_service_v2_client.js
- src/v2/logging_service_v2_client.js
- src/v2/metrics_service_v2_client.js
- system-test/logging.ts
adds a test for the `x-goog-api-client-header` being populated, the fix for `process.version` has already been landed and just needs to be deployed (I made the change manually so that this passes).
> fix: add test for x-goog-api-client header

- src/log.ts
There is a function overload missing in `log.ts` for the function `critical(...)` resulting in a compiler error if `critical` is used as an await function.
> fix: add missing function overload

- package.json
> fix(deps): gcp-metadata now handles ENETUNREACH

- package.json
This gets us on `@grpc/gprc-js@0.6.7`.
> fix(deps): pin to newer version of grpc

- src/log.ts
- test/log.ts
introduces the configuration setting `maxEntrySize` which, if set, will make a best effort to truncate text log entries, such that they don't result in an exception, see:
https://cloud.google.com/logging/quotas
_Note: as follow up, we should set this option to `256,000` on logging-bunyan, and logging-winston._
fixes #427
> feat: introduce maxEntrySize, for enabling error message truncation

- package.json
- src/log.ts
- test/log.ts
our Winston and Bunyan loggers set a variety of additional fields that push us above the `256kb` log limit, I've abstracted the approach we use to allow a set of fields to be truncated ... using :stars: magic :stars:.
> fix: truncate additional fields set by winston/bunyan

- package.json
- src/index.ts
- src/log.ts
- system-test/logging.ts
- test/common.ts
- test/entry.ts
- test/index.ts
- test/log.ts
- test/sink.ts
This just removes a few easy wins.  The only method used by `@google-cloud/common` now is `util.isCustomType`, which will need more specific work to exfiltrate.
> refactor: reduce common dependency

- package.json
This got dropped in https://github.com/googleapis/nodejs-logging/commit/51dd05034abbda44b4781fae1a56c835b8cb8605 but it still being used in `src/metadata.ts`
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #619 🦕
> fix(package): add missing dependency google-auth-library

- src/log.ts
- src/metadata.ts
- test/metadata.ts
BREAKING CHANGE: if using GKE, "Kubernetes Container" type is now properly populated, and logs will be grouped accordingly.
For the gke environment we should populate `k8s_container`, rather than `container`. ~This PR also begins populating `pod_name`, which seems to correlate to `HOST_NAME` in the testing I was doing.~ (reverted this, as it broke tests).
This is a partial fix for #525; there is currently not a good way to get container name, so I've also opened #673.
fixes #525
> fix!: populate k8s_container rather than container

- src/index.ts
This looks more correct to me, but please review!
`gax.GoogleAuthOptions` is a re-export of `require('google-auth-library').GoogleAuthOptions`.
`gax.GrpcClientOptions` extends `GoogleAuthOptions` with these properties: `auth`, `promise`, and `grpc`.
> fix(types): extend constructor options from gax

- synth.py
It now ignores files ignored by github.  Here's the synthtool.metadata it generated:
https://gist.github.com/SurferJeffAtGoogle/5b01fac550bc25294fa4ce8b2ab846d7
> chore: reenable obsolete file tracking

- src/index.ts
- test/index.ts
Fixes #684
`uniqueWriterIdentity` is an exposed option from GAPIC, but we weren't allowing it through.
> feat: support uniqueWriterIdentity in Sink.create

- system-test/logging.ts
Fixes #550 (maybe?)
When logs are attempted to be deleted in the after hook, it isn't thoroughly handling errors:
- Test block (an `it`) gets a reference to a Log (no remote operation, just a Log object)
- Log object is stored in local array (to the `describe`)
- Test block tries to create a log entry, but fails
- After hook iterates over local array of Log objects, but **doesn't know if they were actually created**
This PR just makes sure we're only trying to delete logs that exist.
> test: when cleaning, only delete logs that exist

- samples/logs.js
- src/index.ts
- system-test/logging.ts
- test/index.ts
RE: #550
This adds a new method, `logging.getLogs()` and `logging.getLogsStream()` using the logs.list API: https://cloud.google.com/logging/docs/reference/v2/rest/v2/logs/list
> feat: add getLogs() and getLogsStream()

- system-test/logging.ts
System tests seem to be having an issue with hitting a quota in the after hook:
```
Error: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
```
Likely because we just added the `getLogs()` behavior, which will iteratively make requests until there's no `nextPageToken` provided in the response. They seem to come 100 at a time, so I thought, let's bump it up to 1000 and see if that's quotacceptable.
> test: make less requests to avoid quota limit

- system-test/logging.ts
Fixes #702 
This puts more certainty that failed test log removal results only in `console.warn`s, and not test failure.
> test: ignore getLogs() error in cleanup

- samples/test/quickstart.test.js
- system-test/logging.ts
- test/log.ts
removes the fake failing tests added to test build cop configuration.
> test: remove fake failing tests used to test build-cop

- src/log.ts
- test/log.ts
The test cases for log.write had their assertions within a manual logging service stub for writeLogEntries. If writeLogEntries was never invoked, these tests would still succeed. The refactor for the write test cases use sinon assertion patterns to avoid this scenario. Unit tests for the write suite should now read better, especially as the intention of each test has been refined too.
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
~Fixes #<issue_number_goes_here>~ no open issue for this 🦕
> chore(test): Ensure writeLogEntries is actually called on log write.

- synth.metadata
`synth.metadata` somehow got a bad entry in it (I confirmed locally that the `sha` in the metadata throws an exception).
Fixes: #791
> build: synth.metadata had bad entry
